name: Smart Attendance MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  validate-project:

    runs-on: ubuntu-latest

    steps:

      
      # CHECKOUT REPOSITORY
     

      - name: Checkout Repository
        uses: actions/checkout@v4

      # SETUP PYTHON
    

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # VERIFY PROJECT STRUCTURE
      

      - name: Verify Project Structure
        run: |

          echo "Checking project structure..."

          test -f requirements.txt

          test -f src/api/main.py

          test -f frontend/app.py

          test -f Dockerfile.backend

          test -f Dockerfile.frontend

          echo "Project structure verified!"

     
      # VERIFY YAML FILES
      

      - name: Verify YAML Files
        run: |

          test -f docker-compose.yml

          test -f .github/workflows/ci-cd.yml

          echo "YAML files verified!"

      # VERIFY FRONTEND FILES
   

      - name: Verify Frontend Files
        run: |

          test -f frontend/app.py

          echo "Frontend files verified!"

      # SUCCESS MESSAGE
      

      - name: Pipeline Success
        run: |

          echo "CI/CD Pipeline Executed Successfully!"