name: Smart Attendance MLOps CI/CD Pipeline

on:

  push:

    branches:
      - main

  pull_request:

    branches:
      - main


jobs:

  validate-project:

    runs-on: ubuntu-latest

    env:

      PROJECT_NAME: "Smart Attendance MLOps"

      SIMILARITY_THRESHOLD: "0.70"

      EMBEDDINGS_PATH: "data/embeddings/face_embeddings.pkl"

      MLFLOW_TRACKING_URI: "file:./mlruns"

    steps:

      # CHECKOUT REPOSITORY

      - name: Checkout Repository
        uses: actions/checkout@v4

      # SETUP PYTHON

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: 3.11

      # INSTALL DEPENDENCIES

      - name: Install Dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

      # VERIFY PROJECT STRUCTURE

      - name: Verify Project Structure

        run: |

          echo "Checking project structure..."

          test -f requirements.txt

          test -f src/api/main.py

          test -f frontend/app.py

          test -f Dockerfile.backend

          test -f Dockerfile.frontend

          test -f dvc.yaml

          echo "Project structure verified!"

      # VERIFY YAML FILES

      - name: Verify YAML Files

        run: |

          test -f docker-compose.yml

          test -f .github/workflows/ci-cd.yml

          echo "YAML files verified!"

      # VERIFY PYTHON IMPORTS

      - name: Verify Python Imports

        run: |

          python -c "import fastapi"

          python -c "import streamlit"

          python -c "import mlflow"

          python -c "import dvc"

          echo "Python imports verified!"

      # VERIFY FASTAPI APPLICATION

      - name: Verify FastAPI App

        run: |

          python -c "from src.api.main import app; print('FastAPI working')"

      # VERIFY MLFLOW INTEGRATION

      - name: Verify MLflow Integration

        run: |

          python -c 'from src.mlops.mlflow_manager import start_mlflow_run; print("MLflow working")'

      # VERIFY DVC PIPELINE

      - name: Verify DVC Pipeline

        run: |

          dvc status

      # VERIFY FRONTEND

      - name: Verify Frontend

        run: |

          python -c "from frontend.app import *; print('Frontend working')"

      # SUCCESS MESSAGE

      - name: Pipeline Success

        run: |

          echo "CI/CD Pipeline Executed Successfully!"